// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApi.Models;

namespace MovieApi.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20201127013212_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MovieApi.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateReleased")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sales")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actor = "Daniel Kaluuya, Allison Williams, Bradley Whitford",
                            DateReleased = new DateTime(2017, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A young African American man visits his European American girlfriend's family estate where he learns that many of its residents, who are black, have gone missing, and he soon learns the horrible truth when another frantic African-American warns him to \"get out\". He soon learns this is easier said than done.",
                            Genre = "Horror, Mystery",
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/M/MV5BNTE2Nzg1NjkzNV5BMl5BanBnXkFtZTgwOTgyODMyMTI@._V1_SY500_CR0,0,315,500_AL_.jpg",
                            Sales = 30,
                            Title = "Get Out"
                        },
                        new
                        {
                            Id = 2,
                            Actor = "Chris Buck, Jennifer Lee",
                            DateReleased = new DateTime(2013, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.",
                            Genre = "Animation",
                            ImageUrl = "https://m.media-amazon.com/images/I/61Mbpe16YOL._AC_UL640_FMwebp_QL65_.jpg",
                            Sales = 37,
                            Title = "Frozen"
                        },
                        new
                        {
                            Id = 3,
                            Actor = "Matt Damon, Tommy Lee Jones",
                            DateReleased = new DateTime(2016, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The CIA's most dangerous former operative is drawn out of hiding to uncover more explosive truths about his past.",
                            Genre = "Actio, Thriller",
                            ImageUrl = "https://m.media-amazon.com/images/I/81-1hXkdqDL._AC_UL640_FMwebp_QL65_.jpg",
                            Sales = 28,
                            Title = "Jason Bourne"
                        },
                        new
                        {
                            Id = 4,
                            Actor = "Kevin Hart, Tiffany Haddish",
                            DateReleased = new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A group of high school dropouts are forced to attend night school in hope that they'll pass the GED exam to finish high school.",
                            Genre = "Comedy",
                            ImageUrl = "https://m.media-amazon.com/images/I/71bmSNavewL._AC_UL640_FMwebp_QL65_.jpg",
                            Sales = 110,
                            Title = "Night School"
                        },
                        new
                        {
                            Id = 5,
                            Actor = "Tye Sheridan, Olivia Cooke",
                            DateReleased = new DateTime(2018, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "When the creator of a virtual reality called the OASIS dies, he makes a posthumous challenge to all OASIS users to find his Easter Egg, which will give the finder his fortune and control of his world.",
                            Genre = "Action, Adventure, Sci-Fi",
                            ImageUrl = "https://m.media-amazon.com/images/I/A11LXrQIW3L._AC_UL480_FMwebp_QL65_.jpg",
                            Sales = 52,
                            Title = "Ready Player One"
                        },
                        new
                        {
                            Id = 6,
                            Actor = "James Corden, Judi Dench",
                            DateReleased = new DateTime(2019, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A tribe of cats called the Jellicles must decide yearly which one will ascend to the Heaviside Layer and come back to a new Jellicle life.",
                            Genre = "Comedy, Drama, Family, Fantasy, Musical",
                            ImageUrl = "https://m.media-amazon.com/images/I/81cJ6tvF7tL._AC_UL320_.jpg",
                            Sales = 7,
                            Title = "Cats"
                        },
                        new
                        {
                            Id = 7,
                            Actor = "Benedict Cumberbatch, Cameron Seely ",
                            DateReleased = new DateTime(2018, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A grumpy Grinch (Benedict Cumberbatch) plots to ruin Christmas for the village of Whoville.",
                            Genre = "Animation, Comedy, Family, Fantasy",
                            ImageUrl = "https://m.media-amazon.com/images/I/71v9+cEXjVL._AC_UL640_FMwebp_QL65_.jpg",
                            Sales = 35,
                            Title = "Dr. Seuss' the Grinch"
                        },
                        new
                        {
                            Id = 8,
                            Actor = "Mel Gibson, Walton Goggins",
                            DateReleased = new DateTime(2020, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A rowdy, unorthodox Santa Claus is fighting to save his declining business. Meanwhile, Billy, a neglected and precocious 12 year old, hires a hit man to kill Santa after receiving a lump of coal in his stocking.",
                            Genre = "Action, Comedy, Fantasy, Thriller",
                            ImageUrl = "https://m.media-amazon.com/images/I/81hsWnSLycL._AC_UY327_FMwebp_QL65_.jpg",
                            Sales = 17,
                            Title = "Fatman"
                        },
                        new
                        {
                            Id = 9,
                            Actor = "Lily James, Armie Hammer",
                            DateReleased = new DateTime(2020, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A young newlywed arrives at her husband's imposing family estate on a windswept English coast and finds herself battling the shadow of his first wife, Rebecca, whose legacy lives on in the house long after her death.",
                            Genre = "Drama, Mystery, Romance, Thriller",
                            ImageUrl = "https://m.media-amazon.com/images/I/91Uh9XHJPVL._AC_UL640_FMwebp_QL65_.jpg",
                            Sales = 32,
                            Title = "Rebecca"
                        },
                        new
                        {
                            Id = 10,
                            Actor = "Joaquin Phoenix, Robert De Niro",
                            DateReleased = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.",
                            Genre = "Crime, Drama, Thriller",
                            ImageUrl = "https://m.media-amazon.com/images/I/71YUVzV5OwL._AC_UY436_FMwebp_QL65_.jpg",
                            Sales = 120,
                            Title = "Joker"
                        },
                        new
                        {
                            Id = 11,
                            Actor = "Saoirse Ronan, Emma Watson",
                            DateReleased = new DateTime(2019, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In the years after the Civil War, Jo March (Saoirse Ronan) lives in New York City and makes her living as a writer, while her sister Amy March (Florence Pugh) studies painting in Paris.",
                            Genre = "Drama, Romance",
                            ImageUrl = "https://m.media-amazon.com/images/I/61NVfk2uAXL._AC_UY654_FMwebp_QL65_.jpg",
                            Sales = 117,
                            Title = "Little Women"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
